import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import { RandomFox } from "@/components/RandomFox";
import { IimageItem } from "@/interfaces/Iimage";

const random = (): number => Math.floor(Math.random()*123) + 1
const generateId = () => Math.random().toString(36)

const Home: NextPage = () => {
  const [images, setImages] = useState<IimageItem[]>([
    { id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg`},
    { id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg`},
    { id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg`}
  ])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello fox</h1>
        { images.map(({id, url}) => (
          <div key={id} className="p-4">
            <RandomFox image={url} alt={'A fox'}/>
          </div>
        )) }
        
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;