import type { NextPage } from "next";
import type { MouseEventHandler } from "react";
import { useEffect, useState } from "react";
import Head from "next/head";
import { LazyImage } from "@/components/RandomFox";
import { IimageItem } from "@/interfaces/Iimage";
import { random } from "lodash";

const myRandom = (): number => random(1, 123)
const generateId = () => Math.random().toString(36)

const Home: NextPage = () => {
  const [images, setImages] = useState<IimageItem[]>([
    // { id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg` },
    // { id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg`},
    // { id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg`},
    // { id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg`}
  ])

  // useEffect(() => setImages([{ id: `${generateId()}`, url: `https://randomfox.ca/images/${random()}.jpg` }]), [])

const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
  // event.preventDefault()
  const newImageItem: IimageItem = { id: `${generateId()}`, url: `https://randomfox.ca/images/${myRandom()}.jpg` }
  setImages([
    ...images,
    newImageItem
  ])
}

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello fox</h1>
        <button onClick={addNewFox}>click me</button>
        { images.map(({id, url}, index) => (
          <div key={id} className="p-4">
              <LazyImage
                src={url}
                width="320"
                height="auto"
                className="mx-auto rounded-md bg-gray-300"
                onClick={() => {
                  console.log("holi!");
                }}
                onLazyLoad={(img) => {
                  console.log(`Image #${index + 1} cargada. Nodo:`, img);
                }}
              />
            {/* <LazyImage src={url} 
                  alt={'An image'} 
                  title="random image" 
                  width={320} 
                  height="auto" 
                  className='rounded bg-gray-300'
                  onClick={()=> console.log('click')}/> 
                  si lo hiciera de la otra forma en el componente
                  asi seria un componente generico*/}
          </div>
        )) }
        
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;